name: Build GDExtension

on:
  workflow_call:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  LIBNAME: godot-motion-matching

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: GDExtension Build
        uses: ./.github/actions/build
        with:
          platform: windows
          arch: x86_64
          float-precision: single
          build-target-type: template_debug

      - name: Windows - Delete compilation files
        shell: pwsh
        run: |
          Remove-Item bin/* -Include *.exp,*.lib,*.pdb -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-motion-matching-windows-x86_64-single-template_debug
          path: |
            ${{ github.workspace }}/bin/**
